
<?php
include 'config.php';

if (!isset($_SESSION['admin_logged_in'])) {
    header('Location: login.php');
    exit();
}

$query_num = isset($_GET['query']) ? intval($_GET['query']) : 1;
$patient_id = isset($_GET['patient_id']) ? intval($_GET['patient_id']) : null;
$result = null;
$query_title = '';
$query_description = '';

// Define all queries
$queries = array(
    1 => array(
        'title' => 'Total Revenue Generated',
        'description' => 'Calculate the total revenue generated by the hospital from paid bills',
        'sql' => "SELECT 
                    SUM(b.Amount) AS TotalRevenue,
                    COUNT(b.BID) AS TotalBillsPaid,
                    AVG(b.Amount) AS AverageBillAmount
                FROM bills b
                WHERE b.PaymentStatus = 'Paid'"
    ),
    2 => array(
        'title' => 'Patient Information with Test Reports & Bills',
        'description' => 'Retrieve comprehensive patient details including test reports and billing history',
        'sql' => "SELECT 
                    p.PID, p.Name AS PatientName, p.Age, p.Gender, p.DOB, p.MobNo,
                    t.RID, t.TestType, t.Result, t.TestDate,
                    b.BID, b.Amount, b.PaymentStatus, b.BillDate
                FROM patient p
                LEFT JOIN test_report t ON p.PID = t.PID
                LEFT JOIN bills b ON p.PID = b.PID
                WHERE p.PID = {$patient_id}
                ORDER BY t.TestDate DESC, b.BillDate DESC",
        'requires_patient_id' => true
    ),
    3 => array(
        'title' => 'Patients Diagnosed with Diabetes',
        'description' => 'Retrieve all patients currently diagnosed with diabetes',
        'sql' => "SELECT DISTINCT
                    p.PID, p.Name AS PatientName, p.Age, p.Gender, p.MobNo,
                    t.TestType, t.Result, t.TestDate
                FROM patient p
                INNER JOIN test_report t ON p.PID = t.PID
                WHERE LOWER(t.Result) LIKE '%diabetes%'
                   OR LOWER(t.TestType) LIKE '%diabetes%'
                ORDER BY t.TestDate DESC"
    ),
    4 => array(
        'title' => 'Doctors and Their Departments',
        'description' => 'Retrieve doctor information with department qualification',
        'sql' => "SELECT 
                    d.DoctorID, e.Name AS DoctorName, e.Age, e.Gender, e.MobNo, e.Salary,
                    d.Qualification AS Department,
                    COUNT(c.ConsultID) AS TotalConsultations
                FROM doctor d
                INNER JOIN employee e ON d.DoctorID = e.EID
                LEFT JOIN consults c ON d.DoctorID = c.DoctorID
                GROUP BY d.DoctorID, e.Name, e.Age, e.Gender, e.MobNo, e.Salary, d.Qualification
                ORDER BY d.DoctorID"
    ),
    5 => array(
        'title' => 'Appointments per Doctor by Date',
        'description' => 'Retrieve total number of appointments for each doctor grouped by date',
        'sql' => "SELECT 
                    e.EID AS DoctorID, e.Name AS DoctorName,
                    DATE(c.ConsultDate) AS ConsultationDate,
                    COUNT(c.ConsultID) AS TotalAppointments,
                    d.Qualification
                FROM consults c
                INNER JOIN employee e ON c.DoctorID = e.EID
                INNER JOIN doctor d ON c.DoctorID = d.DoctorID
                GROUP BY e.EID, e.Name, DATE(c.ConsultDate), d.Qualification
                ORDER BY ConsultationDate DESC, e.Name"
    ),
    6 => array(
        'title' => 'Total Bill Amount Paid by Patients',
        'description' => 'Sum of all paid bills grouped by patient',
        'sql' => "SELECT 
                    p.PID, p.Name AS PatientName, p.MobNo,
                    COUNT(b.BID) AS TotalBills,
                    SUM(CASE WHEN b.PaymentStatus = 'Paid' THEN b.Amount ELSE 0 END) AS TotalPaid,
                    SUM(CASE WHEN b.PaymentStatus = 'Pending' THEN b.Amount ELSE 0 END) AS TotalPending,
                    SUM(b.Amount) AS GrandTotal
                FROM patient p
                LEFT JOIN bills b ON p.PID = b.PID
                GROUP BY p.PID, p.Name, p.MobNo
                HAVING SUM(b.Amount) > 0
                ORDER BY TotalPaid DESC"
    ),
    7 => array(
        'title' => 'Patients with Outstanding Bills',
        'description' => 'Retrieve patients with pending/unpaid bills for notification',
        'sql' => "SELECT 
                    p.PID, p.Name AS PatientName, p.MobNo, p.Age,
                    COUNT(b.BID) AS OutstandingBills,
                    SUM(b.Amount) AS TotalOutstandingAmount,
                    MAX(b.BillDate) AS LastBillDate
                FROM patient p
                INNER JOIN bills b ON p.PID = b.PID
                WHERE b.PaymentStatus = 'Pending'
                GROUP BY p.PID, p.Name, p.MobNo, p.Age
                ORDER BY TotalOutstandingAmount DESC"
    ),
    8 => array(
        'title' => 'Male O+ Blood Donors (Disease Free)',
        'description' => 'Male patients with O+ blood group and no disease diagnosis',
        'sql' => "SELECT DISTINCT
                    p.PID, p.Name AS PatientName, p.MobNo, p.Gender, p.Age
                FROM patient p
                WHERE p.Gender = 'Male'
                  AND NOT EXISTS (
                      SELECT 1 FROM test_report t 
                      WHERE t.PID = p.PID 
                      AND LOWER(t.Result) NOT LIKE '%normal%'
                      AND LOWER(t.Result) NOT LIKE '%healthy%'
                  )
                ORDER BY p.Name"
    ),
    9 => array(
        'title' => 'Blood Donors (O-, A-, B-, AB- Negative)',
        'description' => 'Patients with O-, A-, B-, AB- blood groups and disease free',
        'sql' => "SELECT DISTINCT
                    p.PID, p.Name AS PatientName, p.MobNo, p.Gender, p.Age
                FROM patient p
                WHERE NOT EXISTS (
                      SELECT 1 FROM test_report t 
                      WHERE t.PID = p.PID 
                      AND LOWER(t.Result) NOT LIKE '%normal%'
                      AND LOWER(t.Result) NOT LIKE '%healthy%'
                  )
                ORDER BY p.Name"
    )
);

// Get current query
if (isset($queries[$query_num])) {
    $query_data = $queries[$query_num];
    $query_title = $query_data['title'];
    $query_description = $query_data['description'];
    
    // Check if patient ID is required
    if (isset($query_data['requires_patient_id']) && $query_data['requires_patient_id']) {
        if ($patient_id) {
            $result = $conn->query($query_data['sql']);
        }
    } else {
        $result = $conn->query($query_data['sql']);
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Advanced Queries - Hospital Management</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: #f5f6fa;
        }
        
        .navbar {
            /* background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); */
            background: #ce3cefff;
            color: white;
            padding: 20px 40px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        
        .back-btn {
            background: rgba(255,255,255,0.2);
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            text-decoration: none;
        }
        
        .container {
            max-width: 1400px;
            margin: 30px auto;
            padding: 0 20px;
        }
        
        .query-selector {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.08);
        }
        
        .query-selector select {
            padding: 10px;
            border: 2px solid #ddd;
            border-radius: 5px;
            font-size: 16px;
            width: 100%;
        }
        
        .query-info {
            background: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.08);
            border-left: 4px solid #dd66eaff;
        }
        
        .query-info h2 {
            color: #333;
            margin-bottom: 10px;
        }
        
        .query-info p {
            color: #666;
            line-height: 1.6;
        }
        
        table {
            width: 100%;
            background: white;
            border-radius: 10px;
            overflow: hidden;
            box-shadow: 0 5px 15px rgba(0,0,0,0.08);
        }
        
        th, td {
            padding: 15px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        
        th {
            background: #f8f9fa;
            color: #666;
            font-weight: 600;
        }
        
        tr:hover { background: #f8f9fa; }
        
        .no-data {
            text-align: center;
            padding: 40px;
            color: #999;
        }
        
        .form-group {
            margin-bottom: 15px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 5px;
            color: #333;
            font-weight: 500;
        }
        
        .form-group input {
            width: 100%;
            padding: 10px;
            border: 2px solid #ddd;
            border-radius: 5px;
        }
        
        .btn-search {
            background: #ce3cefff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
        }
        
        .btn-search:hover {
            background: #ce3cefff;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <h1>Advanced Queries</h1>
        <a href="dashboard.php" class="back-btn">← Back to Dashboard</a>
    </div>
    
    <div class="container">
        <div class="query-selector">
            <form method="GET" action="">
                <label>Select Query:</label>
                <select name="query" onchange="this.form.submit()">
                    <option value="">-- Select a Query --</option>
                    <option value="1" <?php echo $query_num == 1 ? 'selected' : ''; ?>>Query 01: Total Revenue</option>
                    <option value="2" <?php echo $query_num == 2 ? 'selected' : ''; ?>>Query 02: Patient Info with Reports & Bills</option>
                    <option value="3" <?php echo $query_num == 3 ? 'selected' : ''; ?>>Query 03: Diabetes Patients</option>
                    <option value="4" <?php echo $query_num == 4 ? 'selected' : ''; ?>>Query 04: Doctors & Departments</option>
                    <option value="5" <?php echo $query_num == 5 ? 'selected' : ''; ?>>Query 05: Appointments per Doctor</option>
                    <option value="6" <?php echo $query_num == 6 ? 'selected' : ''; ?>>Query 06: Bills Paid by Patients</option>
                    <option value="7" <?php echo $query_num == 7 ? 'selected' : ''; ?>>Query 07: Outstanding Bills</option>
                    <option value="8" <?php echo $query_num == 8 ? 'selected' : ''; ?>>Query 08: O+ Blood Donors</option>
                    <option value="9" <?php echo $query_num == 9 ? 'selected' : ''; ?>>Query 09: Negative Blood Donors</option>
                </select>
            </form>
        </div>
        
        <?php if ($query_num > 0 && isset($queries[$query_num])): ?>
            <div class="query-info">
                <h2><?php echo $query_title; ?></h2>
                <p><?php echo $query_description; ?></p>
            </div>
            
            <?php if (isset($queries[$query_num]['requires_patient_id']) && $queries[$query_num]['requires_patient_id']): ?>
                <div class="query-selector" style="background: #e3f2fd;">
                    <form method="GET" action="">
                        <div class="form-group">
                            <label>Enter Patient ID:</label>
                            <input type="number" name="patient_id" value="<?php echo $patient_id ?? ''; ?>" required>
                        </div>
                        <input type="hidden" name="query" value="<?php echo $query_num; ?>">
                        <button type="submit" class="btn-search">Search</button>
                    </form>
                </div>
            <?php endif; ?>
            
            <?php if ($result): ?>
                <?php if ($result->num_rows > 0): ?>
                    <table>
                        <thead>
                            <tr>
                                <?php
                                $field_info = $result->fetch_fields();
                                foreach ($field_info as $field) {
                                    echo "<th>" . htmlspecialchars($field->name) . "</th>";
                                }
                                ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php while ($row = $result->fetch_assoc()): ?>
                                <tr>
                                    <?php foreach ($row as $value): ?>
                                        <td><?php echo htmlspecialchars($value ?? 'N/A'); ?></td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endwhile; ?>
                        </tbody>
                    </table>
                <?php else: ?>
                    <div class="no-data">
                        <h3>No Data Found</h3>
                        <p>No records match the current query criteria</p>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</body>
</html>